In [31]:
# import pandas
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# load data
smart_trash = pd.read_csv("smart_trash.csv") 
smart_trash.head(10)

#, index_col="neighborhood"

,container_id,receptacle_model_id,assignment_date,last_updated_date,group_name,address,city,state,zip,neighborhood,dpw_division,council_district,ward,fire_zone,x,y
0,1,74,2017-09-14T13:24:40,2022-11-08T13:17:19,1st Division,122 E North Ave,Pittsburgh,Pennsylvania,15212,Central Northside,1.0,1.0,22.0,1-6,-80.004018,40.456073
1,2,74,2017-09-14T13:24:40,2022-11-08T01:55:34,1st Division,2507 Brighton Rd,Pittsburgh,Pennsylvania,15212,Marshall-Shadeland,1.0,1.0,27.0,1-9,-80.025132,40.467213
2,3,74,2017-09-14T13:24:40,2022-04-14T01:59:18,1st Division,1300 Federal St,Pittsburgh,Pennsylvania,15212,Central Northside,1.0,1.0,22.0,1-6,-80.006872,40.456625
3,4,74,2017-09-14T13:24:40,2022-10-24T12:40:24,1st Division,110 Federal St,Pittsburgh,Pennsylvania,15212,Allegheny Center,1.0,1.0,22.0,1-6,-80.006250,40.454520
4,5,74,2017-09-19T12:22:45,2022-11-08T07:35:23,1st Division,490 E North Ave,Pittsburgh,Pennsylvania,15212,Central Northside,1.0,1.0,22.0,1-6,-80.002083,40.456444
5,6,74,2017-09-19T12:22:46,2022-10-15T13:09:34,1st Division,1501 Brighton Rd,Pittsburgh,Pennsylvania,15212,California-Kirkbride,1.0,6.0,25.0,1-21,-80.015758,40.457025
6,7,74,2017-09-19T12:22:46,2022-06-01T01:34:21,1st Division,3113 Brighton Rd,Pittsburgh,Pennsylvania,15212,Marshall-Shadeland,1.0,1.0,27.0,1-14,-80.029040,40.473820
7,8,74,2017-09-19T12:22:46,2022-11-07T12:07:23,1st Division,1729 Brighton Rd,Pittsburgh,Pennsylvania,15212,California-Kirkbride,1.0,6.0,25.0,1-21,-80.016706,40.459364
8,9,74,2017-09-19T12:22:46,2022-11-08T01:52:15,1st Division,710 W North Ave,Pittsburgh,Pennsylvania,15212,Allegheny Center,1.0,1.0,22.0,1-21,-80.014095,40.453969
9,10,74,2017-09-19T12:22:46,2022-10-15T13:19:20,1st Division,919 Fulton St,Pittsburgh,Pennsylvania,15233,Manchester,1.0,6.0,21.0,1-8,-80.023932,40.451663

In [44]:
#smart_trash.plot()

In [15]:
more_than_1 = lambda x, threshold: x['council_district'].count() > 1

least_councils = smart_trash.groupby("council_district").filter(more_than_1, threshold = 1)

least_councils.groupby("council_district").count()

,container_id,receptacle_model_id,assignment_date,last_updated_date,group_name,address,city,state,zip,dpw_division,ward,fire_zone,x,y
council_district,,,,,,,,,,,,,,
1.0,189,189,189,189,189,189,189,189,189,189,189,189,189,189
2.0,83,83,83,83,83,83,83,83,83,83,83,83,83,83
3.0,121,121,121,121,121,121,121,121,121,121,121,121,121,121
4.0,62,62,62,62,62,62,62,62,62,62,62,62,62,62
5.0,126,126,126,126,126,126,126,126,126,126,126,126,126,126
6.0,142,142,142,142,142,142,142,142,142,142,142,142,142,142
7.0,213,213,213,213,213,213,213,213,213,213,213,213,213,213
8.0,101,101,101,101,101,101,101,101,101,101,101,101,101,101
9.0,156,156,156,156,156,156,156,156,156,156,156,156,156,156

In [43]:
#smart_trash.info()

In [66]:
dropped_data = smart_trash.drop(columns=['container_id', 'receptacle_model_id', 'last_updated_date', 'group_name', 'address', 'city', 'state', 'dpw_division', 'council_district', 'ward', 'fire_zone', 'x', 'y'])
dropped_data.head(20)

        assignment_date    zip          neighborhood
0   2017-09-14T13:24:40  15212     Central Northside
1   2017-09-14T13:24:40  15212    Marshall-Shadeland
2   2017-09-14T13:24:40  15212     Central Northside
3   2017-09-14T13:24:40  15212      Allegheny Center
4   2017-09-19T12:22:45  15212     Central Northside
5   2017-09-19T12:22:46  15212  California-Kirkbride
6   2017-09-19T12:22:46  15212    Marshall-Shadeland
7   2017-09-19T12:22:46  15212  California-Kirkbride
8   2017-09-19T12:22:46  15212      Allegheny Center
9   2017-09-19T12:22:46  15233            Manchester
10  2017-09-19T12:22:46  15214           Perry North
11  2017-09-19T12:22:46  15233    Marshall-Shadeland
12  2017-09-19T12:22:46  15214           Perry North
13  2022-03-09T15:04:33  15212    Marshall-Shadeland
14  2017-09-19T12:22:46  15214           Perry South
15  2017-09-19T12:22:46  15212              Fineview
16  2017-09-19T12:22:46  15233            Manchester
17  2017-09-19T12:22:46  15214           Perry South
18  2017-09-19T12:22:47  15233        Allegheny West
19  2017-09-19T12:22:47  15214           Perry North

In [53]:
#data.groupby("neighborhood").count().head(20)

In [67]:
pivoted_data = dropped_data.pivot(columns="neighborhood", values="zip").count()
pivoted_data.head(50)

neighborhood
NaN                           1
Allegheny Center              7
Allegheny West               15
Allentown                     9
Arlington                     3
Banksville                    2
Bedford Dwellings             1
Beechview                     8
Beltzhoover                   3
Bloomfield                   58
Bluff                        28
Brighton Heights             24
Brookline                    17
California-Kirkbride          4
Carrick                      38
Central Business District     7
Central Lawrenceville        29
Central Northside            10
Central Oakland              34
Chateau                       5
Crafton Heights               8
Crawford-Roberts             21
Duquesne Heights              3
East Allegheny               26
East Carnegie                 1
East Hills                    2
East Liberty                 68
Elliott                      12
Fineview                      3
Friendship                   12
Garfield                      7
Greenfield                   14
Hazelwood                    18
Highland Park                12
Homewood North                4
Homewood South               28
Homewood West                 2
Knoxville                     7
Larimer                      20
Lincoln Place                 7
Lincoln-Lemington-Belmar      6
Lower Lawrenceville          29
Manchester                    6
Marshall-Shadeland           17
Middle Hill                  29
Morningside                   8
Mount Washington             25
Mt. Oliver                    1
North Oakland                14
North Shore                  53
dtype: int64

In [68]:
pivoted_data.max()

76

In [69]:
pivoted_data.min()

1

In [65]:
smart_trash['neighborhood'].value_counts()

Shadyside              76
East Liberty           68
Squirrel Hill South    63
Bloomfield             58
North Shore            53
                       ..
Mt. Oliver              1
East Carnegie           1
Windgap                 1
South Shore             1
Swisshelm Park          1
Name: neighborhood, Length: 79, dtype: int64

In [63]:
smart_trash['neighborhood'].value_counts().tail(10)

Point Breeze North    2
Northview Heights     1
Oakwood               1
St. Clair             1
Bedford Dwellings     1
Mt. Oliver            1
East Carnegie         1
Windgap               1
South Shore           1
Swisshelm Park        1
Name: neighborhood, dtype: int64

In [42]:
#smart_trash['neighborhood'].astype(str)

In [41]:
#data.drop_duplicates(subset=['neighborhood'])

dropped duplicate values in column neighborhood keeping only the first entries